# Generated by Django 4.2.13 on 2024-07-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms_app', '0003_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
